<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVv8plGV\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVv8plGV/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVv8plGV.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVv8plGV\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVv8plGV\appAppKernelProdContainer([
    'container.build_hash' => 'Vv8plGV',
    'container.build_id' => '0704ab2f',
    'container.build_time' => 1675987316,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVv8plGV');
